import MODULE from './module'

export default {
  CREATE_PURCHASE: `@${MODULE}/CREATE_PURCHASE`,
  DELETE_PURCHASE: `@${MODULE}/DELETE_PURCHASE`,
  GET_PURCHASES: `@${MODULE}/GET_PURCHASES`,
  EDIT_PURCHASE: `@${MODULE}/EDIT_PURCHASE`,
  CALCULATE_CASHBACK: `@${MODULE}/CALCULATE_CASHBACK`,
  ADD_CASHBACK: `@${MODULE}/ADD_CASHBACK`,
}
