import MODULE from './module'

export default {
  CREATE_PURCHASE: `@${MODULE}/CREATE_PURCHASE`,
  CREATE_PURCHASE_SUCCESS: `@${MODULE}/CREATE_PURCHASE_SUCCESS`,
  CREATE_PURCHASE_ERROR: `@${MODULE}/CREATE_PURCHASE_ERROR`,
  DELETE_PURCHASE: `@${MODULE}/DELETE_PURCHASE`,
  DELETE_PURCHASE_SUCCESS: `@${MODULE}/DELETE_PURCHASE_SUCCESS`,
  DELETE_PURCHASE_ERROR: `@${MODULE}/DELETE_PURCHASE_ERROR`,
  GET_PURCHASES: `@${MODULE}/GET_PURCHASES`,
  GET_PURCHASES_SUCCESS: `@${MODULE}/GET_PURCHASES_SUCCESS`,
  GET_PURCHASES_ERROR: `@${MODULE}/GET_PURCHASES_ERROR`,
  EDIT_PURCHASE: `@${MODULE}/EDIT_PURCHASE`,
  EDIT_PURCHASE_SUCCESS: `@${MODULE}/EDIT_PURCHASE_SUCCESS`,
  EDIT_PURCHASE_ERROR: `@${MODULE}/EDIT_PURCHASE_ERROR`,
  CALCULATE_CASHBACK: `@${MODULE}/CALCULATE_CASHBACK`,
  ADD_CASHBACK: `@${MODULE}/ADD_CASHBACK`,

  GET_CASHBACK: `@${MODULE}/GET_CASHBACK`,
  GET_CASHBACK_SUCCESS: `@${MODULE}/GET_CASHBACK_SUCCESS`,
  GET_CASHBACK_ERROR: `@${MODULE}/GET_CASHBACK_ERROR`,
}
