import React from 'react'
import { mount } from 'enzyme'
import ErrorBoundary from '../ErrorBoundary'

describe('ErrorBoundary', () => {
  it('should render children correctly', () => {
    const children = <div>test</div>
    let wrapper = mount(<ErrorBoundary>{children}</ErrorBoundary>)

    expect(wrapper).toMatchSnapshot()
    expect(wrapper).toHaveLength(1)
    expect(wrapper.find('div')).toHaveLength(1)
  })

  it('displays error message on error generated by child', () => {
    function ProblemChild() {
      throw new Error('Error thrown from problem child')
      return <div>Error</div> // eslint-disable-line
    }
    let wrapper = mount(
      <ErrorBoundary>
        <ProblemChild />
      </ErrorBoundary>
    )

    expect(wrapper.find('h1')).toHaveLength(1)
  })
})
